#!/bin/bash

#htmlfile - A script to produce an html file

##### Constants

TITLE="My System Information for $HOSTNAME"
RIGHT_NOW=$(date +"%x %r %Z")
TIME_STAMP="Updated on $RIGHT_NOW by $USER"

##### Functions

system_info()
{
	#Temporary function stub
	echo "function system_info"
}

show_uptime()
{
	#Temporary function stub
	echo "function show_uptime"
}	
	

drive_space()
{
	echo "<h2>Filesystem space</h2>
	echo "<pre>"
	df
	echo"</pre>"
}

home_space()
{
	#Temporary function stub
	echo "function home_space"
}

##### Main

cat <<- _EOF_
	<html>
	<head>
		<title>The title of your page: $TITLE</title>
	</head>

	<body>
		Your page content goes here.
	<h1>$TITLE</>
	<p>$TIME_STAMP</p>
	$(system_info)
	$(show_uptime)
	$(drive_space)
	$(home_space)
	</body>
	</heml>
_EOF_
